GET http://localhost:3000/sessions/

###

POST http://localhost:3000/sessions/
content-type: application/json

{
    "date": "2024-05-01T19:00:00.000Z",
    "coach": "661833b94bcc6d0941c4b8d5"
}

###

POST http://localhost:3000/sessions/
content-type: application/json

{
    "date": "2024-05-08T19:00:00.000Z",
    "coach": "661833b94bcc6d0941c4b8d5"
}

###

PUT http://localhost:3000/sessions/661877f0ad10b859afa4d521/coach
content-type: application/json

{
    "coachName": "vlad"
}

###

PUT http://localhost:3000/sessions/661877f0ad10b859afa4d521/attendees/add
content-type: application/json

{
    "attendeeId": "6618338d4bcc6d0941c4b8d4"
}

###

PUT http://localhost:3000/sessions/661877f0ad10b859afa4d521/attendees/remove
content-type: application/json

{
    "attendeeId": "6618338d4bcc6d0941c4b8d4"
}